name: 3L3VAT3D
favicon: null
layout_spectrum: 0.6191682431381196
typography_spectrum: 0.6130468456540257
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfc'
    - '#5c1f1e'
    - '#9e5556'
    - '#c5958d'
    - '#454d49'
  brandStrength: 0.22942378954030573
  lightness: 0.5372277363203466
  saturation: 0.07095557078719139
  rhythmicContrast: 0.4370510426815599
purpose: []
